# Generated by Django 4.0.4 on 2022-07-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='static/uploads')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=75)),
                ('password', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('rating', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=300)),
                ('car_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='imageSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagec', models.ImageField(upload_to='car1')),
                ('car1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_image', to='rentapp.car')),
            ],
        ),
    ]
