# Generated by Django 4.0.4 on 2022-06-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_remove_review_name_review_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='imageSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagec', models.ImageField(upload_to='car1')),
                ('car1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_image', to='rentapp.car')),
            ],
        ),
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('review', models.CharField(max_length=300)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentapp.car', verbose_name='car')),
            ],
        ),
        migrations.DeleteModel(
            name='review',
        ),
    ]
