# Generated by Django 4.0.4 on 2022-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0005_imagesend_reviews_delete_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='usernames',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
