# Generated by Django 4.0.4 on 2022-06-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0006_reviews_usernames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='car',
            new_name='car_name',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='rating',
        ),
    ]
