# Generated by Django 4.0.4 on 2022-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0007_rename_car_reviews_car_name_remove_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='car_name',
            field=models.CharField(max_length=50),
        ),
    ]
